### ISSUE TITLE
Purpose of the fork

### ISSUE THREAD

**Issue by seanwinterberger** [vladmihalcea/tsid#21]
How is this fork being maintained in relation to upstream changes? This fork lacks [ performance updates](https://github.com/f4b6a3/tsid-creator/commit/2d0ebf17fc658e613bbebcc044fe94c6527f392b) upstream has but then this fork has [virtual thread updates](https://github.com/vladmihalcea/hypersistence-tsid/commit/656038d0e74a3d5f7463a9695e6287244ae376e3) the upstream lacks. 

It seems both are active, maybe the upstream is more active, and having this fork is confusing to anyone interested in TSID because your blog links to this repository yet it is 5x slower than the upstream.

If there are no logical changes in this repo other than issues raised by folks who don't realize the original repo is active and package name changes why is the fork being promoted?  It seems the very minor concern raised when forking could have been a PR to the upstream.

**Comment by fabiolimace** [comment]
Hi @seanwinterberger !

First of all, thank you very much for your interest in TSID. I'm the maintainer of the original repository. I also understand that it can be a bit confusing to have two projects that seem to be active for the same purpose.

Respectfully, I do not agree that this project is being promoted more than the original. In fact, it is the opposite: two years ago tsid-creator was completely unknown. I am very grateful for the recognition that my little repository has today.

However, I really do not intend to be as active as I was before in tsid-creator. That is why I had to include a note in the README file stating that the project is in maintenance mode, as I do not see any need to add anything else to it. But I also cannot abandon the repository, as people use its code.

Most updates are just changes to the README. I was planning to bring the final optimizations here to equalize the two, but I did not find the time for that.

In my humble opinion, having alternatives is great because you can choose what best suits your project's needs or your personal preferences.

Finally, thanks again for your interest in TSID!

Best regards,

**Comment by seanwinterberger** [comment]
Apologies @fabiolimace for coming off a bit rough. I was attempting to open an issue against the fork in the interest of merging upstream changes down.

Both projects, the original and fork, have great features/enhancements added.  Of course I can fork this myself and maintain a version with both improvements but realistically almost anyone would want both of these enhancements I linked above.

Thank you @fabiolimace  and @vladmihalcea for working on the project, I am looking forward to testing it out vs ULID.

**Comment by vladmihalcea** [comment]
@seanwinterberger The reason I forked this repository is included in the [README](https://github.com/vladmihalcea/hypersistence-tsid?tab=readme-ov-file#tsid-generator) file. At the time, I wanted to provide a Hibernate integration for TSID, and I was told that the original fork might no longer be maintained.

It's great that @fabiolimace keeps on maintaining the original fork, as he has way more knowledge about the project than I do. So, if you want to choose a generic TSID generator, then choose the original fork.

If you need a TSID identity generator for Hibernate, then you can use this fork since there is not much that this variant has added after the fork.
